# Generated by Django 4.1.3 on 2022-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name_plural': 'Test sets'},
        ),
    ]
